---
title: "PPOL 6801: Text as Data - Computational Linguistics"
subtitle: "McCourt School for Public Policy, Georgetown University"
---

## Course Description

In recent years, the surge in the availability of textual data, ranging from the digitalization of archival documents, political speeches, social media posts, and online news articles, has led to a growing demand for statistical analysis using large volumes of text data. In this course, we will teach students how to analyze and somewhat collect this data from a social science viewpoint. The focus is on understanding the real-world use of text as data rather than just the theory behind it. Students will learn how to acquire text, turn text into data, and analyze it to answer important policy-relevant questions. Each week, we'll go over different methods, like building and using dictionaries, understanding sentiment in text, scaling texts on ideological and policy dimensions, and using machine learning to classify text. Lectures will include hands-on activities, letting students work directly with actual texts, and I strongly encourage students to bring their own data to class. The course aims to equip students with a variety of text analysis techniques that will be valuable for their future work as policy experts and computational social scientists.

While the course covers an interdisciplinary topic, and many of the techniques we discuss have their origins in computer science or statistics, we will spend relatively little time on traditional Natural Language Processing techniques, such as machine translation, optical character recognition, and parts of speech tagging, etc. Although we will touch on Large Language Models (ChatGPT) at the end of the course, we will focus mostly on the practical use of these models through their APIs instead of building up and providing an in-depth understanding of their architecture.

I assume students taking this class have taken, at minimum, an introductory class in statistics and have basic knowledge of probability, distributions, hypothesis testing, and linear models. The core language and software environment of this course is R. If you are not familiar with R, you will struggle with the assigned exercises. We will also provide some code in Python, but no prior knowledge here is assumed since this will be additional material.

## Class Website

<https://tiagoventura.github.io/PPOL_6801_2024/>

## Instructor

[Professor Tiago Ventura](https://www.venturatiago.com/)

-   Pronouns: He/Him
-   Email: [tv186\@georgetown.edu](mailto:tv186@georgetown.edu)
-   Office hours: Every Tuesday, 4pm - 6pm
-   Location: Old north, 312

::: callout-note
### When should I go to your office hours?
:::

**You are all welcome to the office hours.** You can come to the office hours to:

-   drink some coffee;

-   talk about soccer;

-   Ask what I am doing research at;

-   Ask any question about our class.

All are valid options! And no need to schedule time with me!

## Course Infra-structure

**Class Website:** This class website will be used throughout the course and should be checked on a regular basis for lecture materials and required readings.

**Class Slack Channel:** The class also has a dedicated [slack channel](https://join.slack.com/t/ppol68012024/shared_invite/zt-2a4ofec2d-KH8YDtoiJ3gHRWTNhuBPcQ). The channel serves as an open forum to discuss, collaborate, pose problems/questions, and offer solutions. Students are encouraged to pose any questions they have there as this will provide the professor the means of answering the question so that all can see the response. If you're unfamiliar with, please consult the following start-up tutorial <https://get.slack.help/hc/en-us/articles/218080037-Getting-started-for-new-members>. Please follow the [invite link](https://join.slack.com/t/ppol5203fall2023/shared_invite/zt-2159njh4n-S4u1yonz4dA7Zxyo2n3bjA) to be added to the Slack channel.

**Canvas:** A Canvas site <http://canvas.georgetown.edu> will be used throughout the course and should be checked on a regular basis for announcements. Materials will be posted here, and not on canvas, or distributed in class or by e-mail. Support for Canvas is available at (202) 687-4949

## Credits

To build this course, I used materials from Arthur Spirling [Text-as-Data](https://github.com/ArthurSpirling/text-as-data-class-spring2021) Class at NYU, and lab materials from various TA's for his course, Pablo Barbera's [Computational Social Science Seminar](http://pablobarbera.com/POIR613/index.html) seminar, [Brandon Stewart](https://bstewart.scholar.princeton.edu/), [Alex Siegel](https://aasiegel.github.io/website/website-main/), [Chris Bail](https://www.chrisbail.net/), [Sebastian Vallejo](https://www.svallejovera.com/), among others. Their lessons and inspiration are spread throughout all the materials of the course. Thanks!
