---
title: "Week 05"
subtitle: "Supervised Learning II: Training your own classifiers"
description: ""
author: "Tiago Ventura"
date: "02/14/2024"
#listing:
  # - id: slides
  #   contents:
  #     - ../slides/week-01/*.qmd
  #   type: table
  #   fields: [title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     title: "Topic"
  #     date: "Date"
  #   sort: [filename]
  #   sort-ui: false
  #   filter-ui: false
  # - id: assignments
  #   contents:
  #     - ../hw/w1-*.qmd
  #     - ../labs/w1-*.qmd
  #   type: table
  #   fields: [categories, title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     categories: "Assignment"
  #     title: "Title"
  #     date: "Due"
  #   sort: [date]
  #   sort-ui: false
  #   filter-ui: false
tbl-colwidths: [10,50,40]
---

# Topics

We will study the framework to train our own supervised models, and when to use them.

# Readings

**Required Readings**

-   \[GMB\] - Chapters 17, 18, 19, and 20.

-   **Applied Papers**:

    -   Barberá, Pablo, Amber E. Boydstun, Suzanna Linn, Ryan McMahon, and Jonathan Nagler. [Automated text classification of news articles: A practical guide](https://www.cambridge.org/core/journals/political-analysis/article/abs/automated-text-classification-of-news-articles-a-practical-guide/10462DB284B1CD80C0FAE796AD786BC6). Political Analysis 29, no. 1 (2021): 19-42.

    -   Siegel, Alexandra A., Evgenii Nikitin, Pablo Barberá, Joanna Sterling, Bethany Pullen, Richard Bonneau, Jonathan Nagler, and Joshua A. Tucker. [Trumping hate on Twitter? Online hate speech in the 2016 US election campaign and its aftermath](https://www.nowpublishers.com/article/Details/QJPS-19045). Quarterly Journal of Political Science 16, no. 1 (2021): 71-104.

    -   Theocharis, Y., Barberá, P., Fazekas, Z., & Popa, S. A. (2020). [The dynamics of political incivility on Twitter](https://journals.sagepub.com/doi/pdf/10.1177/2158244020919447). Sage Open, 10(2), 2158244020919447.

    -   Mitts, T., Phillips, G., & Walter, B. (2021). [Studying the Impact of ISIS Propaganda Campaigns](https://www.journals.uchicago.edu/doi/abs/10.1086/716281). Journal of Politics

**Coding Materials**

-   <a href="/code/week5_supervised_learning.R" download> Week 5 - Supervised Learning: Training your own classifiers</a>

# Slides

-   [Week 5 - Supervised Learning](/slides/week_05.html)
