---
title: "Week 02"
subtitle: "From Text to Matrices: Representing Text as Data"
description: ""
#author: "Tiago Ventura"
date: "01/24/2024"
#listing:
  # - id: slides
  #   contents:
  #     - ../slides/week-01/*.qmd
  #   type: table
  #   fields: [title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     title: "Topic"
  #     date: "Date"
  #   sort: [filename]
  #   sort-ui: false
  #   filter-ui: false
  # - id: assignments
  #   contents:
  #     - ../hw/w1-*.qmd
  #     - ../labs/w1-*.qmd
  #   type: table
  #   fields: [categories, title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     categories: "Assignment"
  #     title: "Title"
  #     date: "Due"
  #   sort: [date]
  #   sort-ui: false
  #   filter-ui: false
tbl-colwidths: [10,50,40]
---

# Topics

-   How to represent text as data?
-   What is a Bag of Words?
-   What are tokens?
-   Why should we care about tokens?

# Readings

**Required Readings**

-   Grimmer, Justin, Margaret E. Roberts, and Brandon M. Stewart. Text as data: A new framework for machine learning and the social sciences. Princeton University Press, 2022 - Chapters 3-5

-   **Applied Papers**:

-   [Denny, M. J., & Spirling, A. (2018). Text preprocessing for unsupervised learning: why it matters, when it misleads, and what to do about it. Political Analysis, 26(2): 168-189](https://www.cambridge.org/core/journals/political-analysis/article/text-preprocessing-for-unsupervised-learning-why-it-matters-when-it-misleads-and-what-to-do-about-it/AA7D4DE0AA6AB208502515AE3EC6989E).

-   [Ban, Pamela, Alexander Fouirnaies, Andrew B. Hall, and James M. Snyder. "How newspapers reveal political power." Political Science Research and Methods 7, no. 4 (2019): 661-678.](https://www.cambridge.org/core/journals/political-science-research-and-methods/article/how-newspapers-reveal-political-power/683B2D970E88A25239276D6FA071632B)

-   [Michel, J.B., et al. 2011. "Quantitative Analysis of Culture Using Millions of Digitized Books." Science 331 (6014): 176--82. https://doi.org/10.1126/science.1199644](https://www.science.org/doi/10.1126/science.1199644)

**Coding Materials**

- <a href="/code/week2_introduction_to_text_analysis.R" download> Week 2 - Text Data Processing </a> 

# Slides

-   [Week 2 - From Text to Matrices: Representing Text as Data](/slides/week_02.html)

