---
title: "Week 04"
subtitle: "Supervised Learning I: Dictionary Methods and Off-the-Shelf Classifiers"
description: ""
author: "Tiago Ventura"
date: "02/07/2024"
#listing:
  # - id: slides
  #   contents:
  #     - ../slides/week-01/*.qmd
  #   type: table
  #   fields: [title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     title: "Topic"
  #     date: "Date"
  #   sort: [filename]
  #   sort-ui: false
  #   filter-ui: false
  # - id: assignments
  #   contents:
  #     - ../hw/w1-*.qmd
  #     - ../labs/w1-*.qmd
  #   type: table
  #   fields: [categories, title, date]
  #   date-format: "ddd, MMM DD"
  #   field-display-names:
  #     categories: "Assignment"
  #     title: "Title"
  #     date: "Due"
  #   sort: [date]
  #   sort-ui: false
  #   filter-ui: false
tbl-colwidths: [10,50,40]
---

# Topics

-   What are dictionaries?

-   Why/when are they useful?

-   What are their limitations?

-   Can we use models trained by others and for other purposes in our classification tasks?

# Readings

**Required Readings**

-   \[GMB\] - Chapters 15-16

-   **Applied Papers**:

    -   Lori Young and Stuart Soroka 2012 "Affective News: The Automated Coding of Sentiment in Political Texts." Political Communication, 29:2, 205-231.

    -   Rathje, Steve, Jay J. Van Bavel, and Sander Van Der Linden. "Out-group animosity drives engagement on social media." Proceedings of the National Academy of Sciences 118, no. 26 (2021): e2024292118.

    -   Ventura, Tiago, Kevin Munger, Katherine McCabe, and Keng-Chi Chang. "Connective effervescence and streaming chat during political debates." Journal of Quantitative Description: Digital Media 1 (2021).

**Coding Materials**

-    <a href="/code/week4_dictionaries.R" download> Week 4 - Dictionaries and Off-the-Shelf Classifiers</a>

-  <a href="/code/week4_transformers.R" download> Week 4 - Transformers Based Classifiers </a>

# Problem set 1

-   [Problem Set 1](https://classroom.github.com/a/M3UZZ4rz)

# Slides

-   [Week 4 - Dictionaries and Off-the-Shelf Classifiers](/slides/week_04.html)
